language: node_js
node_js:
- '0.12'
before_install:
- npm install npm -g
before_script:
- npm install
script: npm run ci
addons:
  sauce_connect: true
env:
  global:
    - secure: JIuVK8uLIFzfPTjcOfkbNsYw9Od0ZFqIB0Ex0ymOXEuNffrsnwvwdJ4EvQo1QN8Qp3znWDBnxW3tQ0auJa38Mj6WExoxPJ5mlUMW/KmJ4UmkkpeOSIr58xuNOaHqa7a9d29xhjp8O+EdeVlwFjYa/MajT12W8RYfOa2/2hmnu2k=
    - secure: MTbfzmX90a9qLEYrfLQQADYDYJ4jTds3GyXWkd3zvOjI7MnQxTKRhix6fyeeq2wprHgKWcitcpaGwEwPDaPCz5/PIN/ZWrOnqwL/lBaFJ37jPSn6WQyubwZm/TU9XdQal+E6+xmoalpiMmWCSYcF4NQVyymrsKja5YMkWWbudTU=
